[module]
  [module.hugoVersion]
    min = "0.73.0"
  [[module.imports]]
    path = "github.com/kaushalmodi/hugo-debugprint"
  [[module.imports]]
    path = "github.com/kaushalmodi/hugo-search-fuse-js"
